/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPatientsRouteImport } from './routes/_app/patients'
import { Route as AppSegmentsSegmentIdRouteImport } from './routes/_app/segments/$segmentId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSegmentsSegmentIdRoute = AppSegmentsSegmentIdRouteImport.update({
  id: '/segments/$segmentId',
  path: '/segments/$segmentId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/patients': typeof AppPatientsRoute
  '/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
}
export interface FileRoutesByTo {
  '/patients': typeof AppPatientsRoute
  '/': typeof AppIndexRoute
  '/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/patients': typeof AppPatientsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patients' | '/segments/$segmentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/patients' | '/' | '/segments/$segmentId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/patients'
    | '/_app/'
    | '/_app/segments/$segmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/segments/$segmentId': {
      id: '/_app/segments/$segmentId'
      path: '/segments/$segmentId'
      fullPath: '/segments/$segmentId'
      preLoaderRoute: typeof AppSegmentsSegmentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppPatientsRoute: typeof AppPatientsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSegmentsSegmentIdRoute: typeof AppSegmentsSegmentIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPatientsRoute: AppPatientsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSegmentsSegmentIdRoute: AppSegmentsSegmentIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
