/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPatientsRouteImport } from './routes/_app/patients'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppDemoIndexRouteImport } from './routes/_app/demo/index'
import { Route as AppEhrIndexRouteImport } from './routes/_app/ehr/index'
import { Route as AppSegmentsSegmentIdRouteImport } from './routes/_app/segments/$segmentId'
import { Route as AppEhrPrescriptionsPatientIdRouteImport } from './routes/_app/ehr/prescriptions/$patientId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDemoIndexRoute = AppDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEhrIndexRoute = AppEhrIndexRouteImport.update({
  id: '/ehr/',
  path: '/ehr/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSegmentsSegmentIdRoute = AppSegmentsSegmentIdRouteImport.update({
  id: '/segments/$segmentId',
  path: '/segments/$segmentId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEhrPrescriptionsPatientIdRoute =
  AppEhrPrescriptionsPatientIdRouteImport.update({
    id: '/ehr/prescriptions/$patientId',
    path: '/ehr/prescriptions/$patientId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/patients': typeof AppPatientsRoute
  '/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
  '/audit/': typeof AppAuditIndexRoute
  '/demo/': typeof AppDemoIndexRoute
  '/ehr/': typeof AppEhrIndexRoute
  '/ehr/prescriptions/$patientId': typeof AppEhrPrescriptionsPatientIdRoute
}
export interface FileRoutesByTo {
  '/patients': typeof AppPatientsRoute
  '/': typeof AppIndexRoute
  '/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
  '/audit': typeof AppAuditIndexRoute
  '/demo': typeof AppDemoIndexRoute
  '/ehr': typeof AppEhrIndexRoute
  '/ehr/prescriptions/$patientId': typeof AppEhrPrescriptionsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/patients': typeof AppPatientsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/segments/$segmentId': typeof AppSegmentsSegmentIdRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/demo/': typeof AppDemoIndexRoute
  '/_app/ehr/': typeof AppEhrIndexRoute
  '/_app/ehr/prescriptions/$patientId': typeof AppEhrPrescriptionsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients'
    | '/segments/$segmentId'
    | '/audit/'
    | '/demo/'
    | '/ehr/'
    | '/ehr/prescriptions/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/patients'
    | '/'
    | '/segments/$segmentId'
    | '/audit'
    | '/demo'
    | '/ehr'
    | '/ehr/prescriptions/$patientId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/patients'
    | '/_app/'
    | '/_app/segments/$segmentId'
    | '/_app/audit/'
    | '/_app/demo/'
    | '/_app/ehr/'
    | '/_app/ehr/prescriptions/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/demo/': {
      id: '/_app/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof AppDemoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ehr/': {
      id: '/_app/ehr/'
      path: '/ehr'
      fullPath: '/ehr/'
      preLoaderRoute: typeof AppEhrIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/segments/$segmentId': {
      id: '/_app/segments/$segmentId'
      path: '/segments/$segmentId'
      fullPath: '/segments/$segmentId'
      preLoaderRoute: typeof AppSegmentsSegmentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ehr/prescriptions/$patientId': {
      id: '/_app/ehr/prescriptions/$patientId'
      path: '/ehr/prescriptions/$patientId'
      fullPath: '/ehr/prescriptions/$patientId'
      preLoaderRoute: typeof AppEhrPrescriptionsPatientIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppPatientsRoute: typeof AppPatientsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSegmentsSegmentIdRoute: typeof AppSegmentsSegmentIdRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppDemoIndexRoute: typeof AppDemoIndexRoute
  AppEhrIndexRoute: typeof AppEhrIndexRoute
  AppEhrPrescriptionsPatientIdRoute: typeof AppEhrPrescriptionsPatientIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPatientsRoute: AppPatientsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSegmentsSegmentIdRoute: AppSegmentsSegmentIdRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppDemoIndexRoute: AppDemoIndexRoute,
  AppEhrIndexRoute: AppEhrIndexRoute,
  AppEhrPrescriptionsPatientIdRoute: AppEhrPrescriptionsPatientIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
